### ISSUE TITLE
Rationale for class design?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocSet#2]
Is there a reason that `BiocSet` doesn't use the `Vector` hierarchy? It seems like you could get a lot of things for free with the `ROWS` generics, e.g., subsetting, ordering, see `?sameAsPreviousROW`. (To me, the most obvious `Vector` semantics would be to make the object parallel to the sets.)

And now for the self-interest. My analysis stack relies on being able to set and get `metadata()` on Bioconductor objects, and the fact that `BiocSet` doesn't play by those rules breaks my setup. Even just having `setClass("BiocSet", contains="Annotated")` would be a start.

**Comment by mtmorgan** [comment]
There was quite a bit of discussion about this at https://community-bioc.slack.com/archives/CEK3JDXFV with several different implementations; The Vectors route explored was with Hits to represent sets. I guess at the end of the day the design decision was mine, with the feeling that gene set annotation / enrichment is particularly user-facing and my sense that the tidyverse is more accessible to users than Hits. I also thought the exploration of coordination between tibbles with relations between them was worth exploring.

We won't implement `setClass("BiocSet", contains = "Annotated")`.

**Comment by lawremi** [comment]
Assuming we can still have a discussion even if the issue won't be fixed, I think we should be careful about viewing user-facing and software-facing interfaces as mutually exclusive. It should be possible to have a programmatic and user-friendly interface to the same data structure (like plyranges). The tricky bit is that R users expect object transparency, which at least superficially is antithetical to encapsulation and abstraction, and thus precludes dual interfaces. However, the BiocSet object is already a "weird" S4 object despite containing tibbles, so transparency is already lost. None of this is stopping someone from making a Vector derivative that decorates BiocSet, with an API that delegates to it.
