### ISSUE TITLE
OBO question and bug report?

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocSet#3]
Hi @Kayla-Morrell 
Thank you for doing all the work on this. 
I noticed that some colleagues in the Waldron lab can make use of the OBO file importing. 
Can I refer them to this `exportOBO` branch? 

BTW
The second line overwrites the first error output. Was this intentional? 

https://github.com/Bioconductor/BiocSet/blob/0ca64d84d5750fef08a724178728d824fca89e12/R/OBOSet-class.R#L39-L40

**Comment by Kayla-Morrell** [comment]
Hello @LiNk-NY 
The branch is still very much under development as we figure out the best way to represent the data in the obo files. Feel free to make your colleagues aware of it but they should be cautious as nothing is final just yet. Though we hope to have the final code ready soon.

Thank you for pointing out the overwriting code, I'll take a look and make any necessary changes.

**Comment by LiNk-NY** [comment]
Thanks Kayla! :+1:
