### ISSUE TITLE
Performing filter operations on BiocSet does not alter element list

### ISSUE THREAD

**Issue by qpmnguyen** [Bioconductor/BiocSet#4]
Hi! 

I noticed that when applying a `filter` operation on sets (i.e. using `filter_set()`), the resulting `elementset` and `set` changes but the `elements` did not change. In other words, if I just filter my set collection to one set, the number of elements is still the original number of elements before any filtering was done. 

``` r
library(BiocSet)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
set_list <- list(set1 = sample(LETTERS,4), set2 = sample(LETTERS,4), set3 = sample(LETTERS,4))
set_bioc <- BiocSet(set_list)
set_bioc
#> class: BiocSet
#> 
#> es_element():
#> # A tibble: 9 x 1
#>   element
#>   <chr>  
#> 1 L      
#> 2 T      
#> 3 K      
#> # … with 6 more rows
#> 
#> es_set():
#> # A tibble: 3 x 1
#>   set  
#>   <chr>
#> 1 set1 
#> 2 set2 
#> 3 set3 
#> 
#> es_elementset() <active>:
#> # A tibble: 12 x 2
#>   element set  
#>   <chr>   <chr>
#> 1 L       set1 
#> 2 T       set1 
#> 3 K       set1 
#> # … with 9 more rows
set_bioc <- set_bioc %>% es_activate(set) %>% filter(set == "set1")
set_bioc
#> class: BiocSet
#> 
#> es_element():
#> # A tibble: 9 x 1
#>   element
#>   <chr>  
#> 1 L      
#> 2 T      
#> 3 K      
#> # … with 6 more rows
#> 
#> es_set() <active>:
#> # A tibble: 1 x 1
#>   set  
#>   <chr>
#> 1 set1 
#> 
#> es_elementset():
#> # A tibble: 4 x 2
#>   element set  
#>   <chr>   <chr>
#> 1 L       set1 
#> 2 T       set1 
#> 3 K       set1 
#> # … with 1 more row
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
 
In the example above, I filtered my set collection to only set 1 which has 4 elements, but the number of elements is still 9 from the original. 

I was wondering if this is intended or if this is a bug? Thank you so much!

**Comment by Kayla-Morrell** [comment]
@qpmnguyen - Thank you for asking your question, this behavior is intended.  If you use `filter_set()` you will see the changes in `set` as well as `elementset`, as we wanted to preserve the `element` information . If you wanted to perform the filter so that it changes all of them, I would suggest using `filter_elementset()`, like below.

```{r}
> set_list <- list(set1 = sample(LETTERS,4), set2 = sample(LETTERS,4), set3 = sample(LETTERS,4))
> set_bioc <- BiocSet(set_list)
> set_bioc %>% filter_elementset(set == "set1")
class: BiocSet

es_element():
# A tibble: 4 x 1
  element
  <chr>
1 M
2 P
3 L
# … with 1 more row

es_set():
# A tibble: 1 x 1
  set
  <chr>
1 set1

es_elementset() <active>:
# A tibble: 4 x 2
  element set
  <chr>   <chr>
1 M       set1
2 P       set1
3 L       set1
# … with 1 more row
>
```

Hope this helps.
-Kayla

**Comment by qpmnguyen** [comment]
Thank you very much this was super helpful! 

My intention was to filter sets based on added information (e.g. p-values). I think according to your solution I should attach this external information to both `set` and `elementset` and then filter by `elementset`.  

I will close this issue now. Thank you again for the help!
